INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('ORDER_AMOUNT_FOR_FREE_DELIVERY', 0, false, true, now(), 1, now(), 1);
	
INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('DELIVERY_CHARGE_DELIVERY_BOY_BELOW_MIN_ORDERS', 10, false, true, now(), 1, now(), 1);
	
INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('DELIVERY_CHARGE_DELIVERY_BOY_ABOVE_MIN_ORDERS', 15, false, true, now(), 1, now(), 1);