ALTER TABLE ORDERS ADD COLUMN REFUNDED BOOLEAN DEFAULT FALSE;
ALTER TABLE ORDERS ADD COLUMN PAYMENT_DATE TIMESTAMP WITH TIME ZONE;
ALTER TABLE ORDERS ADD COLUMN DELIVERY_DATE TIMESTAMP WITH TIME ZONE;