ALTER TABLE TASK RENAME COLUMN AMOUNT_BORNE_BY_ADMIN TO ADMIN_PROFIT;
ALTER TABLE TASK RENAME COLUMN AMOUNT_BORNE_BY_DELIVERY_BOY TO DELIVERY_BOY_PROFIT;
ALTER TABLE TASK RENAME COLUMN AMOUNT_BORNE_BY_VENDOR TO VENDOR_PROFIT;
