ALTER TABLE IF EXISTS CUSTOMER_ADDRESS ADD COLUMN LATITUDE NUMERIC(19, 2);
ALTER TABLE IF EXISTS CUSTOMER_ADDRESS ADD COLUMN LONGITUDE NUMERIC(19, 2);
ALTER TABLE IF EXISTS DISCOUNT ADD COLUMN CATEGORY_ID BIGINT NOT NULL;
ALTER TABLE IF EXISTS DISCOUNT ADD COLUMN VENDOR_ID BIGINT NOT NULL;
ALTER TABLE IF EXISTS PRODUCT ADD COLUMN DISCOUNT_ID BIGINT;