ALTER TABLE TASK ADD COLUMN AMOUNT_BORNE_BY_ADMIN NUMERIC(10,2);
ALTER TABLE TASK ADD COLUMN AMOUNT_BORNE_BY_DELIVERY_BOY NUMERIC(10,2);
ALTER TABLE TASK ADD COLUMN AMOUNT_BORNE_BY_VENDOR NUMERIC(10,2);