
ALTER TABLE DELIVERY_BOY DROP COLUMN if exists IS_LOGIN;
ALTER TABLE DELIVERY_BOY DROP COLUMN if exists IS_BUSY;
ALTER TABLE IF EXISTS DELIVERY_BOY ADD COLUMN STATUS VARCHAR(255) NOT NULL;
ALTER TABLE IF EXISTS ONLINE_CART ADD COLUMN DELIVERY_TYPE VARCHAR(255) NOT NULL;
ALTER TABLE IF EXISTS ONLINE_CART ADD COLUMN LATITUDE NUMERIC(10, 6) NOT NULL;
ALTER TABLE IF EXISTS ONLINE_CART ADD COLUMN LONGITUDE NUMERIC(10, 6) NOT NULL;
ALTER TABLE IF EXISTS ORDERS ADD COLUMN LONGITUDE NUMERIC(10, 6) NOT NULL;
ALTER TABLE IF EXISTS ORDERS ADD COLUMN ASSIGNMENT_TRY_COUNT INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS ORDERS ADD COLUMN DELIVERY_TYPE VARCHAR(255) NOT NULL;
ALTER TABLE IF EXISTS ORDERS ADD COLUMN LATITUDE NUMERIC(10, 6) NOT NULL;
ALTER TABLE IF EXISTS ORDERS ADD COLUMN NOTIFICATION_TIMER TIME WITH TIME ZONE DEFAULT CURRENT_TIME;
ALTER TABLE IF EXISTS TASK ADD COLUMN DELIVERED_DATE TIMESTAMP WITH TIME ZONE ;
ALTER TABLE IF EXISTS VENDOR ADD COLUMN MAX_DAYS_FOR_ACCEPT INTEGER;

CREATE TABLE IF NOT EXISTS DELIVERY_BOY_CURRENT_STATUS
(
    ID BIGSERIAL NOT NULL,
 	CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  	CREATED_BY NUMERIC(10,0) NOT NULL,
  	UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,		
  	UPDATED_BY NUMERIC(10,0) NOT NULL,
  	ACTIVE BOOLEAN NOT NULL,
    IS_AVAILABLE BOOLEAN NOT NULL,
    IS_BUSY BOOLEAN NOT NULL,
    IS_LOGIN BOOLEAN NOT NULL,
    DELIVERY_BOY_ID BIGINT NOT NULL,
    CONSTRAINT DELIVERY_BOY_CURRENT_STATUS_PKEY PRIMARY KEY (ID),
    CONSTRAINT DELIVERY_BOY_CURRENT_STATUS_DELIVERY_BOY_UNIQUE UNIQUE (DELIVERY_BOY_ID),
    CONSTRAINT DELIVERY_BOY_CURRENT_STATUS_DELIVERY_BOY FOREIGN KEY (DELIVERY_BOY_ID)
        REFERENCES DELIVERY_BOY (ID) 
);

