ALTER TABLE IF EXISTS TICKET ADD COLUMN TICKET_REASON_ID BIGINT NOT NULL;
ALTER TABLE IF EXISTS TICKET ADD CONSTRAINT TICKET_TICKET_REASON FOREIGN KEY (TICKET_REASON_ID) REFERENCES TICKET_REASON;
ALTER TABLE TICKET DROP COLUMN TICKET_REASON; 