ALTER TABLE TASK RENAME COLUMN PAYMENT_DETAILS_ID TO DELIVERY_BOY_PAYMENT_DETAILS_ID;
ALTER TABLE TASK ADD COLUMN VENDOR_PAYMENT_DETAILS_ID BIGINT;
ALTER TABLE TASK ADD CONSTRAINT VEND_PAY_FK FOREIGN KEY (VENDOR_PAYMENT_DETAILS_ID) REFERENCES PAYMENT_DETAILS(ID);