CREATE TABLE IF NOT EXISTS AREA(
    ID BIGSERIAL NOT NULL,
	CITY_ID BIGINT NOT NULL,
	NAME_ENGLISH CHARACTER VARYING(255) NOT NULL,
    NAME_ARABIC CHARACTER VARYING(255) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CONSTRAINT AREA_PKEY PRIMARY KEY (ID),
	CONSTRAINT AREA_CITY FOREIGN KEY (CITY_ID)
		REFERENCES CITY (ID)
);
