CREATE TABLE IF NOT EXISTS BUSINESS_CATEGORY
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
	IMAGE_NAME CHARACTER VARYING(255),
	ORIGINAL_IMAGE_NAME CHARACTER VARYING(255),
	MANAGE_INVENTORY BOOLEAN NOT NULL,
    CONSTRAINT VENDOR_CATEGORY_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SUBSCRIPTION_PLAN
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
	AMOUNT   NUMERIC(10,2) NOT NULL,
	DAYS INTEGER NOT NULL,
	IMAGE_NAME CHARACTER VARYING(255),
	ORIGINAL_IMAGE_NAME CHARACTER VARYING(255),
    CONSTRAINT SUBSCRIPTION_PLAN_PKEY PRIMARY KEY (ID)
);
