CREATE TABLE IF NOT EXISTS TEMP_CART_ITEM
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UUID CHARACTER VARYING(255) NOT NULL,
    PRODUCT_VARIANT_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT TEMP_CART_ITEM_PKEY PRIMARY KEY (ID),
    CONSTRAINT TEMP_CART_ITEM_PRODUCT_VARIANT FOREIGN KEY (PRODUCT_VARIANT_ID)
        REFERENCES PRODUCT_VARIANT (ID)
);

CREATE TABLE IF NOT EXISTS TEMP_CART_ADDONS
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    TEMP_CART_ITEM_ID BIGINT NOT NULL,
    PRODUCT_ADDONS_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT TEMP_CART_ADDONS_PKEY PRIMARY KEY (ID),
    CONSTRAINT TEMP_CART_ADDONS_TEMP_CART FOREIGN KEY (TEMP_CART_ITEM_ID)
        REFERENCES TEMP_CART_ITEM (ID),
    CONSTRAINT TEMP_CART_ADDONS_PRODUCT_ADDONS FOREIGN KEY (PRODUCT_ADDONS_ID)
        REFERENCES PRODUCT_ADDONS (ID)
);

CREATE TABLE IF NOT EXISTS TEMP_CART_EXTRAS
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    TEMP_CART_ITEM_ID BIGINT NOT NULL,
    PRODUCT_EXTRAS_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT TEMP_CART_EXTRAS_PKEY PRIMARY KEY (ID),
    CONSTRAINT TEMP_CART_EXTRAS_TEMP_CART FOREIGN KEY (TEMP_CART_ITEM_ID)
        REFERENCES TEMP_CART_ITEM (ID),
    CONSTRAINT TEMP_CART_EXTRAS_PRODUCT_ADDONS FOREIGN KEY (PRODUCT_EXTRAS_ID)
        REFERENCES PRODUCT_EXTRAS (ID)
);

CREATE TABLE IF NOT EXISTS TEMP_CART_PRODUCT_ATTRIBUTE
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    TEMP_CART_ITEM_ID BIGINT NOT NULL,
    PRODUCT_ATTRIBUTE_VALUE_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT TEMP_CART_PROD_ATTR_PKEY PRIMARY KEY (ID),
    CONSTRAINT TEMP_CART_PROD_ATTR_TEMP_CART FOREIGN KEY (TEMP_CART_ITEM_ID)
        REFERENCES TEMP_CART_ITEM (ID),
    CONSTRAINT TEMP_CART_PROD_ATTR_PRODUCT_ATTR_VAL FOREIGN KEY (PRODUCT_ATTRIBUTE_VALUE_ID)
        REFERENCES  PRODUCT_ATTRIBUTE_VALUES (ID)
);

CREATE TABLE IF NOT EXISTS TEMP_CART_TOPPINGS
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    TEMP_CART_ITEM_ID BIGINT NOT NULL,
    PRODUCT_TOPPINGS_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT TEMP_CART_TOPPINGS_PKEY PRIMARY KEY (ID),
    CONSTRAINT TEMP_CART_TOPPINGS_TEMP_CART FOREIGN KEY (TEMP_CART_ITEM_ID)
        REFERENCES TEMP_CART_ITEM (ID),
    CONSTRAINT TEMP_CART_ADDONS_PRODUCT_TOPPINGS FOREIGN KEY (PRODUCT_TOPPINGS_ID)
        REFERENCES PRODUCT_TOPPING (ID)
);

CREATE TABLE IF NOT EXISTS CART_ITEM
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    PRODUCT_VARIANT_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    ONLINE_PAYMENT_ORDER_ID CHARACTER VARYING(255),
    ONLINE_CART_ID BIGINT,
    ONLINE_ORDER_ID VARCHAR(255),
    CONSTRAINT CART_ITEM_PKEY PRIMARY KEY (ID),
    CONSTRAINT CART_ITEM_PRODUCT_VARIANT FOREIGN KEY (PRODUCT_VARIANT_ID)
        REFERENCES PRODUCT_VARIANT (ID),
    CONSTRAINT CART_ITEM_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (ID)
);

CREATE TABLE IF NOT EXISTS CART_ADDONS
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CART_ITEM_ID BIGINT NOT NULL,
    PRODUCT_ADDONS_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT CART_ADDONS_PKEY PRIMARY KEY (ID),
    CONSTRAINT CART_ADDONS_CART FOREIGN KEY (CART_ITEM_ID)
        REFERENCES CART_ITEM (ID),
    CONSTRAINT CART_ADDONS_PRODUCT_ADDONS FOREIGN KEY (PRODUCT_ADDONS_ID)
        REFERENCES PRODUCT_ADDONS (ID)
);

CREATE TABLE IF NOT EXISTS CART_EXTRAS
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CART_ITEM_ID BIGINT NOT NULL,
    PRODUCT_EXTRAS_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT CART_EXTRAS_PKEY PRIMARY KEY (ID),
    CONSTRAINT CART_EXTRAS_CART FOREIGN KEY (CART_ITEM_ID)
        REFERENCES CART_ITEM (ID),
    CONSTRAINT CART_EXTRAS_PRODUCT_ADDONS FOREIGN KEY (PRODUCT_EXTRAS_ID)
        REFERENCES PRODUCT_EXTRAS (ID)
);

CREATE TABLE IF NOT EXISTS CART_PRODUCT_ATTRIBUTE
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CART_ITEM_ID BIGINT NOT NULL,
    PRODUCT_ATTRIBUTE_VALUE_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT CART_PROD_ATTR_PKEY PRIMARY KEY (ID),
    CONSTRAINT CART_PROD_ATTR_CART FOREIGN KEY (CART_ITEM_ID)
        REFERENCES CART_ITEM (ID),
    CONSTRAINT CART_PROD_ATTR_PRODUCT_ATTR_VAL FOREIGN KEY (PRODUCT_ATTRIBUTE_VALUE_ID)
        REFERENCES  PRODUCT_ATTRIBUTE_VALUES (ID)
);

CREATE TABLE IF NOT EXISTS CART_TOPPINGS
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CART_ITEM_ID BIGINT NOT NULL,
    PRODUCT_TOPPINGS_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    CONSTRAINT CART_TOPPINGS_PKEY PRIMARY KEY (ID),
    CONSTRAINT CART_TOPPINGS_CART FOREIGN KEY (CART_ITEM_ID)
        REFERENCES CART_ITEM (ID),
    CONSTRAINT CART_ADDONS_PRODUCT_TOPPINGS FOREIGN KEY (PRODUCT_TOPPINGS_ID)
        REFERENCES PRODUCT_TOPPING (ID)
);