CREATE TABLE IF NOT EXISTS CASH_COLLECTION
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    AMOUNT DOUBLE PRECISION NOT NULL,
    PAID_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    DELIVERY_BOY_ID BIGINT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    TASK_ID BIGINT NOT NULL,
    CONSTRAINT CASH_COLLECTION_PKEY PRIMARY KEY (ID),
    CONSTRAINT CASH_COLLECTION_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ID) ,
    CONSTRAINT CASH_COLLECTION_TASK FOREIGN KEY (TASK_ID)
        REFERENCES TASK (ID),
    CONSTRAINT CASH_COLLECTION_DELIVERY_BOY FOREIGN KEY (DELIVERY_BOY_ID)
        REFERENCES DELIVERY_BOY (ID)
);