CREATE TABLE IF NOT EXISTS CUISINE
(
    ID BIGSERIAL NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
	ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    IMAGE_NAME CHARACTER VARYING(255),
	IMAGE_ORIGINAL_NAME CHARACTER VARYING(255),
   	CONSTRAINT CUISINE_PKEY PRIMARY KEY (ID),
    CONSTRAINT CUISINE_UKEY UNIQUE (NAME)
);
