ALTER TABLE DELIVERY_BOY
ADD COLUMN IS_PHONE_NUMBER_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE CATEGORY
ADD COLUMN VENDOR_ID BIGINT NOT NULL;

ALTER TABLE IF EXISTS CATEGORY ADD CONSTRAINT CATEGORY_VENDOR
  FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR;

CREATE TABLE  IF NOT EXISTS DELIVERY_BOY_SEND_NOTIFICATION_HISTORY
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    ORDER_ID BIGINT,
    DELIVERY_BOY_ID BIGINT NOT NULL,
    CONSTRAINT DELIVERY_BOY_SEND_NOTIFICATION_HISTORY_PKEY PRIMARY KEY (ID),
    CONSTRAINT DELIVERY_BOY_SEND_NOTIFICATION_HISTORY_DELIVERY_BOY_ID_UNIQUE UNIQUE (DELIVERY_BOY_ID),
    CONSTRAINT DELIVERY_BOY_SEND_NOTIFICATION_HISTORY_DELIVERY_BOY FOREIGN KEY (DELIVERY_BOY_ID)
        REFERENCES DELIVERY_BOY (ID)
);
