CREATE TABLE IF NOT EXISTS DELIVERY_BOY_ACTIVE_TIME(
	ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
	CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    RECORD_DATE DATE NOT NULL, 
    DELIVERY_BOY_ID BIGINT NOT NULL,
    ACTIVE_TIME_MINUTES NUMERIC(4,0) NOT NULL,
    CONSTRAINT DELIVERY_BOY_ACTIVE_TIME_PKEY PRIMARY KEY (ID),
    CONSTRAINT DELIVERY_BOY_ACTIVE_TIME_DELIVERY_BOY FOREIGN KEY (DELIVERY_BOY_ID)
        REFERENCES DELIVERY_BOY (ID)
);

ALTER TABLE DELIVERY_BOY_CURRENT_STATUS ADD COLUMN LAST_ACTIVATE_TIME TIMESTAMP WITH TIME ZONE;