ALTER TABLE DELIVERY_BOY RENAME COLUMN FIRST_NAME TO FIRST_NAME_ENGLISH;
ALTER TABLE DELIVERY_BOY RENAME COLUMN LAST_NAME TO LAST_NAME_ENGLISH;
ALTER TABLE DELIVERY_BOY RENAME COLUMN BANK_NAME TO BANK_NAME_ENGLISH;
ALTER TABLE DELIVERY_BOY RENAME COLUMN BRANCH_NAME TO BRANCH_NAME_ENGLISH;
ALTER TABLE DELIVERY_BOY RENAME COLUMN ACCOUNT_NAME TO ACCOUNT_NAME_ENGLISH;
ALTER TABLE DELIVERY_BOY RENAME COLUMN BRANCH_CITY TO BRANCH_CITY_ENGLISH;

ALTER TABLE DELIVERY_BOY ADD COLUMN FIRST_NAME_ARABIC CHARACTER VARYING(255) DEFAULT ' ' NOT NULL;
ALTER TABLE DELIVERY_BOY ADD COLUMN LAST_NAME_ARABIC CHARACTER VARYING(255) DEFAULT ' ' NOT NULL;
ALTER TABLE DELIVERY_BOY ADD COLUMN BANK_NAME_ARABIC CHARACTER VARYING(255);
ALTER TABLE DELIVERY_BOY ADD COLUMN BRANCH_NAME_ARABIC CHARACTER VARYING(255);
ALTER TABLE DELIVERY_BOY ADD COLUMN ACCOUNT_NAME_ARABIC CHARACTER VARYING(255);
ALTER TABLE DELIVERY_BOY ADD COLUMN BRANCH_CITY_ARABIC CHARACTER VARYING(255);
