
CREATE TABLE IF NOT EXISTS DEVICE_DETAIL
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    DEVICE_ID CHARACTER VARYING(255) NOT NULL,
    USER_TYPE CHARACTER VARYING(255) NOT NULL,
    DEVICE_TYPE CHARACTER VARYING(255) NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT DEVICE_DETAIL_PKEY PRIMARY KEY (ID),
    CONSTRAINT DEVICE_DETAIL_USER_LOGIN FOREIGN KEY (USER_ID)
        REFERENCES USER_LOGIN (ID),
    UNIQUE (USER_TYPE, DEVICE_ID)
);