CREATE TABLE IF NOT EXISTS DISCOUNT
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,  
    TOTAL_PRODUCTS INTEGER,
    DISCOUNT_RATE NUMERIC(10,2) NOT NULL,
    END_DATE DATE NOT NULL,
    START_DATE DATE NOT NULL,
    STATUS CHARACTER VARYING(255) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    VENDOR_ID BIGINT NOT NULL,
    CONSTRAINT DISCOUNT_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DISCOUNT_APPLIED_PRODUCT_HISTORY
(
    ID BIGSERIAL NOT NULL,
    DISCOUNT_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
	STATUS CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT DISCOUNT_APPLIED_PRODUCT_HISTORY_PKEY PRIMARY KEY (ID)
);

