ALTER TABLE ORDERS ALTER COLUMN LATITUDE DROP NOT NULL;
ALTER TABLE ORDERS ALTER COLUMN LONGITUDE DROP NOT NULL;

ALTER TABLE STOCK_ALLOCATION ALTER COLUMN DELIVERY_BOY_ID DROP NOT NULL;
ALTER TABLE STOCK_ALLOCATION ALTER COLUMN TASK_ID DROP NOT NULL;