CREATE TABLE IF NOT EXISTS HTML_SECTION
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    SECTION_VALUE TEXT NOT NULL,
	SECTION_TYPE  CHARACTER VARYING(255),
    CONSTRAINT SECTION_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SLIDER_IMAGE
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    IMAGE_NAME CHARACTER VARYING(255) NOT NULL,
    ORIGIONAL_IMAGE_NAME CHARACTER VARYING(255) NOT NULL,
  	IMAGE_TYPE CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT SLIDER_BANNER_PKEY PRIMARY KEY (ID)
);

	
	
	
