CREATE TABLE IF NOT EXISTS CATEGORY
(
    ID BIGSERIAL NOT NULL,
	ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    IMAGE CHARACTER VARYING(255),
    IMAGE_ORIGINAL_NAME CHARACTER VARYING(255),
    NAME CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT CATEGORY_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SUB_CATEGORY
(
    ID BIGSERIAL NOT NULL,
	ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    IMAGE CHARACTER VARYING(255),
    IMAGE_ORIGINAL_NAME CHARACTER VARYING(255),
    NAME CHARACTER VARYING(255) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    CONSTRAINT SUB_CATEGORY_PKEY PRIMARY KEY (ID),
    CONSTRAINT SUB_CATEGORY_CATEGORY FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY (ID)
 );     

  CREATE TABLE IF NOT EXISTS BRAND
(
    ID BIGSERIAL NOT NULL,
	ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT BRAND_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ROLE
(
    ID BIGSERIAL NOT NULL,
	ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    DESCRIPTION CHARACTER VARYING(255),
    NAME CHARACTER VARYING(255),
    CONSTRAINT ROLE_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MODULES
(
    ID BIGSERIAL NOT NULL,
	ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    NAME CHARACTER VARYING(255),
    CONSTRAINT MODULES_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PERMISSION
(
    ID BIGSERIAL NOT NULL,
	ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CAN_ADD BOOLEAN,
    CAN_DELETE BOOLEAN,
    CAN_EDIT BOOLEAN,
    CAN_EXPORT BOOLEAN,
    CAN_IMPORT BOOLEAN,
    CAN_VIEW BOOLEAN,
    CAN_VIEW_LIST BOOLEAN,
    MODULES_ID BIGINT,
    ROLE_ID BIGINT,
    CONSTRAINT PERMISSION_PKEY PRIMARY KEY (ID),
    CONSTRAINT PERMISSION_MODULES FOREIGN KEY (MODULES_ID)
        REFERENCES MODULES (ID),
    CONSTRAINT PERMISSION_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ID)
);
