INSERT INTO COUNTRY (NAME_ENGLISH,NAME_ARABIC, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ACTIVE) VALUES ('Kuwait','الكويت', NOW(), 1, NOW(), 1, true);
INSERT INTO STATE (NAME_ARABIC,NAME_ENGLISH, COUNTRY_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ACTIVE) VALUES ('الكويت','Kuwait', 1, NOW(), 1, NOW(), 1, true);
