INSERT INTO SCHEDULER_DETAILS (NAME, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('VENDOR_SUBSCRIPTION_EXPIRE',TRUE, NOW(),1, NOW(), 1);
INSERT INTO SCHEDULER_DETAILS (NAME, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('VENDOR_SUBSCRIPTION_EXPIRE_REMINDER',TRUE, NOW(),1, NOW(), 1);
INSERT INTO SCHEDULER_DETAILS (NAME, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('EXPIRE_STOCK_SCHEDULER',TRUE, NOW(),1, NOW(), 1);
INSERT INTO SCHEDULER_DETAILS (NAME, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('ACTIVATE_EXPIRE_DISCOUNT',true, NOW(),1, NOW(), 1);
