INSERT INTO USER_LOGIN(
	ENTITY_ID, ENTITY_TYPE, EMAIL, PASSWORD, ROLE_ID, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES (null,null,'kodytest.2020@gmail.com', '$2a$12$WMEtIan7v/2U8b2pnCRHb.zm/TH488DlUtZzYo0bSOyfBZT.yaZRa',1,true, now(), 1,now(), 1);   
