CREATE TABLE IF NOT EXISTS STOCK_DETAILS
(
    ID BIGSERIAL NOT NULL,
	LOT_NO NUMERIC(7,2),
    AVAILABLE NUMERIC(7,2) NOT NULL,
    RESERVED NUMERIC(7,2) NOT NULL,
    DELIVERED NUMERIC(7,2) NOT NULL,
    REPLACED NUMERIC(7,2) NOT NULL,
    RETURNED NUMERIC(7,2) NOT NULL,
    EXPIRED NUMERIC(7,2) NOT NULL,
	PRODUCT_VARIANT_ID 	BIGINT NOT NULL,
	VENDOR_ID 	BIGINT NOT NULL,
	ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
	LOT_DATE  DATE  NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	CONSTRAINT STOCK_DETAILS_PKEY PRIMARY KEY (ID),
	 CONSTRAINT VENDOR_STOCK_FK FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
         CONSTRAINT PRODUCT_VARIENT_STOCK FOREIGN KEY (PRODUCT_VARIANT_ID)
        REFERENCES PRODUCT_VARIANT (ID)
);


CREATE TABLE IF NOT EXISTS STOCK_TRANSFER
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
	TRANSFERED_FROM CHARACTER VARYING(255),
    TRANSFERED_TO CHARACTER VARYING(255),
    STOCK_DETAILS_ID BIGINT NOT NULL,
	VENDOR_ID 	BIGINT,
    ORDER_ID BIGINT ,
    ORDER_FROM CHARACTER VARYING(255) DEFAULT 'WEBSITE',
    QUANTITY DOUBLE PRECISION NOT NULL,
    IS_MANUAL BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT STOCK_TRANSFER_PKEY PRIMARY KEY (ID),
      CONSTRAINT VENDOR_STOCK_TRANSFER_FK FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
         CONSTRAINT STOCK_DETAILS_TRANSFER FOREIGN KEY (STOCK_DETAILS_ID)
        REFERENCES STOCK_DETAILS (ID)
);