CREATE TABLE IF NOT EXISTS ONLINE_CART
(
    ID BIGSERIAL NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  	CREATED_BY NUMERIC(10,0) NOT NULL,
  	UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,		
  	UPDATED_BY NUMERIC(10,0) NOT NULL,	
  	ACTIVE BOOLEAN NOT NULL,
	ADDRESS CHARACTER VARYING(255) NOT NULL,
    CITY_ID BIGINT NOT NULL,
    FIRST_NAME CHARACTER VARYING(255)  NOT NULL,
    LAST_NAME CHARACTER VARYING(255)  NOT NULL,
    ONLINE_ORDER_ID CHARACTER VARYING(255),
    PAYMENT_AMOUNT DOUBLE PRECISION,
    PHONE_NUMBER CHARACTER VARYING(255)  NOT NULL,
    PINCODE_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    STATE_ID BIGINT NOT NULL,
    STATUS CHARACTER VARYING(255) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    PRODUCT_VARIANT_ID BIGINT NOT NULL,
    CONSTRAINT ONLINE_CART_PKEY PRIMARY KEY (ID),
    CONSTRAINT ONLINE_CART_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (ID) ,
    CONSTRAINT ONLINE_CART_PRODUCT_VARIANT_FK FOREIGN KEY (PRODUCT_VARIANT_ID)
        REFERENCES PRODUCT_VARIANT (ID)
);

CREATE TABLE IF NOT EXISTS ONLINE_ADDONS
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ONLINE_CART_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    PRODUCT_ADDONS_ID BIGINT NOT NULL,
    CONSTRAINT ONLINE_ADDONS_PKEY PRIMARY KEY (ID),
    CONSTRAINT ONLINE_ADDONS_PRODUCT_ADDONS_FK FOREIGN KEY (PRODUCT_ADDONS_ID)
        REFERENCES PRODUCT_ADDONS (ID)
);

CREATE TABLE IF NOT EXISTS ONLINE_EXTRAS
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ONLINE_CART_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
   	PRODUCT_EXTRAS_ID BIGINT NOT NULL,
    CONSTRAINT ONLINE_EXTRAS_PKEY PRIMARY KEY (ID),
    CONSTRAINT ONLINE_EXTRAS_PRODUCT_EXTRAS_FK FOREIGN KEY (PRODUCT_EXTRAS_ID)
        REFERENCES PRODUCT_EXTRAS (ID) 
);

CREATE TABLE IF NOT EXISTS ONLINE_PRODUCT_ATTRIBUTE
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ONLINE_CART_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    PRODUCT_ATTRIBUTE_VALUE_ID BIGINT NOT NULL,
    CONSTRAINT ONLINE_PRODUCT_ATTRIBUTE_PKEY PRIMARY KEY (ID),
    CONSTRAINT ONLINE_PRODUCT_ATTRIBUTE_PRODUCT_ATTRIBUTE_VALUE_FK FOREIGN KEY (PRODUCT_ATTRIBUTE_VALUE_ID)
        REFERENCES PRODUCT_ATTRIBUTE_VALUES (ID)
);

CREATE TABLE IF NOT EXISTS ONLINE_TOPPINGS
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ONLINE_CART_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    PRODUCT_TOPPINGS_ID BIGINT NOT NULL,
    CONSTRAINT ONLINE_TOPPINGS_PKEY PRIMARY KEY (ID),
    CONSTRAINT ONLINE_TOPPINGS_PRODUCT_TOPPINGS_FK FOREIGN KEY (PRODUCT_TOPPINGS_ID)
        REFERENCES PRODUCT_TOPPING (ID)
);

 ALTER TABLE IF EXISTS CART_ITEM ADD COLUMN ONLINE_CART_ID BIGINT;
 ALTER TABLE IF EXISTS CART_ITEM ADD COLUMN ONLINE_ORDER_ID VARCHAR(255);