ALTER TABLE ORDERS DROP COLUMN RETURN_REPLACE_REASON;
ALTER TABLE ORDERS DROP COLUMN CANCEL_REASON;
ALTER TABLE ORDERS ADD COLUMN RETURN_REPLACE_CANCEL_REJECT_REASON_ID BIGINT;
ALTER TABLE ORDERS ADD CONSTRAINT REASON_FK FOREIGN KEY (RETURN_REPLACE_CANCEL_REJECT_REASON_ID) REFERENCES TICKET_REASON(ID);