ALTER TABLE ORDERS_ITEM ADD COLUMN REPLACE_REQUESTED BOOLEAN NOT NULL DEFAULT FALSE; 
ALTER TABLE ORDERS_ITEM ADD COLUMN RETURN_REQUESTED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ORDERS_ITEM ADD COLUMN RETURN_REPLACE_QUANTITY INT;