CREATE TABLE IF NOT EXISTS ORDER_LOCATION
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    LATITUDE NUMERIC(10,6) NOT NULL,
    LONGITUDE NUMERIC(10,6) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    DELIVERY_BOY_ID BIGINT NOT NULL,	
   	ORDER_ID BIGINT NOT NULL,
    CONSTRAINT ORDER_LOCATION_PKEY PRIMARY KEY (ID) 
);