ALTER TABLE ORDERS RENAME COLUMN ADDRESS TO ADDRESS_ENGLISH;
ALTER TABLE ORDERS ADD COLUMN ADDRESS_ARABIC TEXT NOT NULL DEFAULT '';
ALTER TABLE ORDERS ADD COLUMN DISTANCE NUMERIC(6,2);


ALTER TABLE ONLINE_CART RENAME COLUMN ADDRESS TO ADDRESS_ENGLISH;
ALTER TABLE ONLINE_CART ADD COLUMN ADDRESS_ARABIC TEXT NOT NULL DEFAULT '';
