CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,  
    CATEGORY_ID BIGINT NOT NULL,
    DESCRIPTION CHARACTER VARYING(255) NOT NULL,
    IMAGE CHARACTER VARYING(255) NOT NULL,
    IMAGE_ORIGINAL_NAME CHARACTER VARYING(255) NOT NULL, 
    NAME CHARACTER VARYING(255) NOT NULL,
    SUBCATEGORY_ID BIGINT,
    BRAND_ID BIGINT,
    VENDOR_ID BIGINT NOT NULL,
    CUISINE_ID BIGINT,
    PRODUCT_AVAILABLE BOOLEAN,
    COMBO BOOLEAN DEFAULT FALSE,
    RATING NUMERIC(7,2) NOT NULL DEFAULT 0,
	NO_OF_RATING BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PRODUCT_PKEY PRIMARY KEY (ID),
    CONSTRAINT PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY (ID),
    CONSTRAINT PRODUCT_SUBCATEGORY FOREIGN KEY (SUBCATEGORY_ID)
        REFERENCES SUB_CATEGORY (ID),
    CONSTRAINT PRODUCT_VARIANT_VENDOR FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID), 
	CONSTRAINT PRODUCT_BRAND FOREIGN KEY (BRAND_ID)
        REFERENCES BRAND (ID),
    CONSTRAINT PRODUCT_CUISINE FOREIGN KEY (CUISINE_ID)
        REFERENCES CUISINE (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_VARIANT
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,  
    DISCOUNTED_RATE NUMERIC(10,2),
    RATE NUMERIC(10,2) NOT NULL,
    SKU CHARACTER VARYING(255),
    PRODUCT_ID BIGINT NOT NULL,
    UOM_ID BIGINT NOT NULL,
    VENDOR_ID BIGINT NOT NULL,
    PRODUCT_AVAILABLE BOOLEAN,
    CONSTRAINT PRODUCT_VARIANT_PKEY PRIMARY KEY (ID),
    CONSTRAINT PRODUCT_VARIANT_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT (ID),
    CONSTRAINT PRODUCT_VARIANT_UOM FOREIGN KEY (UOM_ID)
        REFERENCES UOM (ID),
    CONSTRAINT PRODUCT_VARIANT_VENDOR FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
    CONSTRAINT PRODUCT_VARIANT_UNQ UNIQUE(PRODUCT_ID, VENDOR_ID, UOM_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_RATE_UPDATE_HISTORY
(
    ID BIGSERIAL NOT NULL,
    NEW_DISCOUNTED_RATE NUMERIC(10,2),
    NEW_RATE NUMERIC(10,2),
    OLD_DISCOUNTED_RATE NUMERIC(10,2),
    OLD_RATE NUMERIC(10,2),
    PRODUCT_VARIANT_ID BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,  
 	CONSTRAINT PRODUCT_RATE_UPDATE_HISTORY_PKEY PRIMARY KEY (ID)
);