ALTER TABLE PRODUCT RENAME COLUMN NAME TO NAME_ENGLISH;
ALTER TABLE PRODUCT ADD COLUMN NAME_ARABIC TEXT;
ALTER TABLE PRODUCT RENAME COLUMN DESCRIPTION TO DESCRIPTION_ENGLISH;
ALTER TABLE PRODUCT ADD COLUMN DESCRIPTION_ARABIC TEXT;

ALTER TABLE ADDONS RENAME COLUMN NAME TO NAME_ENGLISH;
ALTER TABLE ADDONS ADD COLUMN NAME_ARABIC TEXT;
ALTER TABLE ADDONS RENAME COLUMN DESCRIPTION TO DESCRIPTION_ENGLISH;
ALTER TABLE ADDONS ADD COLUMN DESCRIPTION_ARABIC TEXT;

ALTER TABLE TOPPING RENAME COLUMN NAME TO NAME_ENGLISH;
ALTER TABLE TOPPING ADD COLUMN NAME_ARABIC TEXT;
ALTER TABLE TOPPING RENAME COLUMN DESCRIPTION TO DESCRIPTION_ENGLISH;
ALTER TABLE TOPPING ADD COLUMN DESCRIPTION_ARABIC TEXT;

ALTER TABLE PRODUCT_EXTRAS_MASTER RENAME COLUMN NAME TO NAME_ENGLISH;
ALTER TABLE PRODUCT_EXTRAS_MASTER ADD COLUMN NAME_ARABIC TEXT;
ALTER TABLE PRODUCT_EXTRAS_MASTER RENAME COLUMN DESCRIPTION TO DESCRIPTION_ENGLISH;
ALTER TABLE PRODUCT_EXTRAS_MASTER ADD COLUMN DESCRIPTION_ARABIC TEXT;

ALTER TABLE PRODUCT_ATTRIBUTE RENAME COLUMN NAME TO NAME_ENGLISH;
ALTER TABLE PRODUCT_ATTRIBUTE ADD COLUMN NAME_ARABIC TEXT;
ALTER TABLE PRODUCT_ATTRIBUTE RENAME COLUMN DESCRIPTION TO DESCRIPTION_ENGLISH;
ALTER TABLE PRODUCT_ATTRIBUTE ADD COLUMN DESCRIPTION_ARABIC TEXT;

ALTER TABLE PRODUCT_ATTRIBUTE_VALUES RENAME COLUMN ATTRIBUTE_VALUE TO ATTRIBUTE_VALUE_ENGLISH;
ALTER TABLE PRODUCT_ATTRIBUTE_VALUES ADD COLUMN ATTRIBUTE_VALUE_ARABIC TEXT;
ALTER TABLE PRODUCT_ATTRIBUTE_VALUES RENAME COLUMN DESCRIPTION TO DESCRIPTION_ENGLISH;
ALTER TABLE PRODUCT_ATTRIBUTE_VALUES ADD COLUMN DESCRIPTION_ARABIC TEXT;

ALTER TABLE ORDERS_TOPPINGS DROP COLUMN TOPPINGS_NAME;
ALTER TABLE ORDERS_EXTRAS DROP COLUMN EXTRAS_NAME;
ALTER TABLE ORDERS_ADDONS DROP COLUMN ADDONS_NAME;
ALTER TABLE ORDERS_PRODUCT_ATTRIBUTE DROP COLUMN ATTRIBUTE_NAME;
ALTER TABLE ORDERS_PRODUCT_ATTRIBUTE DROP COLUMN ATTRIBUTE_VALUE;