	
CREATE TABLE IF NOT EXISTS PRODUCT_ATTRIBUTE
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
	VENDOR_ID BIGINT NOT NULL, 
    DESCRIPTION CHARACTER VARYING(255),
    CONSTRAINT PRODUCT_ATTRIBUTE_PKEY PRIMARY KEY (ID),
	CONSTRAINT PRODUCT_ATTR_VENDOR_fK FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
    CONSTRAINT PRODUCT_ATTR_VENDOR_NAME_UNQ UNIQUE(VENDOR_ID, NAME)
);

CREATE TABLE IF NOT EXISTS PRODUCT_ATTRIBUTE_VALUES(
 
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    PRODUCT_ATTRIBUTE_ID BIGINT NOT NULL, 
    ATTRIBUTE_VALUE CHARACTER VARYING(255) NOT NULL,
    PRODUCT_VARIANT_ID BIGINT NOT NULL, 
    DESCRIPTION CHARACTER VARYING(255),
    RATE  NUMERIC(10,2) NOT NULL,
    CONSTRAINT PRODUCT_ATTRIBUTE_VALUES_PKEY PRIMARY KEY (ID),
	CONSTRAINT PRODUCT_ATTR_PRODUCT_ATTR_VALUE_fK FOREIGN KEY (PRODUCT_ATTRIBUTE_ID)
        REFERENCES PRODUCT_ATTRIBUTE (ID),
	CONSTRAINT PRODUCT_PRODUCT_ATTR_VALUE_fK FOREIGN KEY (PRODUCT_VARIANT_ID)
        REFERENCES PRODUCT_VARIANT (ID),
    CONSTRAINT PROD_ATTR_VAL_VARIANT_ATTR_VAL_UNQ UNIQUE(PRODUCT_ATTRIBUTE_ID, ATTRIBUTE_VALUE, PRODUCT_VARIANT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_EXTRAS (

    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
	VENDOR_ID BIGINT NOT NULL, 
	PRODUCT_ID BIGINT,
	RATE  NUMERIC(10,2),
    DESCRIPTION CHARACTER VARYING(255),
    CONSTRAINT PRODUCT_EXTRAS_PKEY PRIMARY KEY (ID),
	CONSTRAINT PRODUCT_EXTRAS_VENDOR_fK FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
	CONSTRAINT PRODUCT_EXTRAS_PRODUCT_fK FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT (ID),
    CONSTRAINT PRODUCT_EX_PROD_NAME_UNQ UNIQUE(PRODUCT_ID, NAME)
        
 );