CREATE TABLE IF NOT EXISTS PRODUCT_TOPPING
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,  
	NAME CHARACTER VARYING(255) NOT NULL,
    DESCRIPTION CHARACTER VARYING(255),
    RATE NUMERIC(10,2) NOT NULL,
    PRODUCT_VARIANT_ID BIGINT NOT NULL,
    VENDOR_ID BIGINT NOT NULL,
    PRODUCT_FOOD_TYPE CHARACTER VARYING(255),
    CONSTRAINT PRODUCT_TOPPING_PKEY PRIMARY KEY (ID),
    CONSTRAINT PRODUCT_TOPPING_VARIANT FOREIGN KEY (PRODUCT_VARIANT_ID)
        REFERENCES PRODUCT_VARIANT (ID), 
    CONSTRAINT PRODUCT_VARIANT_VENDOR FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
	CONSTRAINT VENDOR_TOPPING_NAME_UNIQUE UNIQUE(VENDOR_ID, NAME, PRODUCT_VARIANT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_ADDONS
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,  
	NAME CHARACTER VARYING(255) NOT NULL,
    DESCRIPTION CHARACTER VARYING(255),
    RATE NUMERIC(10,2) NOT NULL,
    PRODUCT_VARIANT_ID BIGINT NOT NULL,
    VENDOR_ID BIGINT NOT NULL,
    PRODUCT_FOOD_TYPE CHARACTER VARYING(255),
    CONSTRAINT PRODUCT_ADDONS_PKEY PRIMARY KEY (ID),
    CONSTRAINT PRODUCT_ADDONS_VARIANT FOREIGN KEY (PRODUCT_VARIANT_ID)
        REFERENCES PRODUCT_VARIANT (ID), 
    CONSTRAINT PRODUCT_VARIANT_VENDOR FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
	CONSTRAINT VENDOR_ADDONS_NAME_UNIQUE UNIQUE(VENDOR_ID, NAME, PRODUCT_VARIANT_ID)
);