ALTER TABLE USERS ADD COLUMN IF NOT EXISTS PREFERRED_LANGUAGE CHARACTER VARYING(20) NOT NULL;

CREATE TABLE IF NOT EXISTS PUSH_NOTIFICATION
(
    ID BIGSERIAL,
    ENTITY_ID BIGINT NOT NULL,
    ENTITY_TYPE CHARACTER VARYING(255) NOT NULL,
    MESSAGE_ARABIC CHARACTER VARYING(255) NOT NULL,
    MESSAGE_ENGLISH CHARACTER VARYING(255) NOT NULL,
    SUCCESS_ALL BOOLEAN NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CONSTRAINT PUSH_NOTIFICATION_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUSH_NOTIFICATION_RECEIVER
(
    ID BIGSERIAL,
    PUSH_NOTIFICATION_ID BIGINT NOT NULL,
    SENDER_ID BIGINT NOT NULL,
    RECEIVER_ID BIGINT NOT NULL,
    DEVICE_ID CHARACTER VARYING(255) NOT NULL,
    MESSAGE_ARABIC CHARACTER VARYING(255) NOT NULL,
    MESSAGE_ENGLISH CHARACTER VARYING(255) NOT NULL,
    SUCCESS BOOLEAN NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CONSTRAINT PUSH_NOTIFICATION_RECEIVER_PKEY PRIMARY KEY (ID),
    CONSTRAINT PUSH_NOTIFICATION_RECEIVER_FK FOREIGN KEY (PUSH_NOTIFICATION_ID) REFERENCES PUSH_NOTIFICATION(ID)
);