CREATE TABLE IF NOT EXISTS ORDER_RATING
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
	ORDER_ID BIGINT NOT NULL,
	VENDOR_ID BIGINT NOT NULL,
	DELIVERY_BOY_ID BIGINT,
	ORDER_PACKING_RATING    NUMERIC(7,2),
	FOOD_QUALITY_RATING     NUMERIC(7,2),
	VALUE_FOR_MONEY_RATING  NUMERIC(7,2),
	DELIVERY_BOY_RATING    NUMERIC(7,2),
	RESTAURANT_RATING      NUMERIC(7,2),
	REVIEW CHARACTER VARYING(255),
    CONSTRAINT ORDER_RATING_PKEY PRIMARY KEY (ID),
	CONSTRAINT ORDER_RATING_VENDOR_fK FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
	CONSTRAINT ORDER_RATING_BOY_fK FOREIGN KEY (DELIVERY_BOY_ID)
        REFERENCES DELIVERY_BOY (ID)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEM_RATING
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    ITEM_RATING NUMERIC(7,2),
	ORDER_RATING_ID BIGINT NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
    CONSTRAINT ORDER_ITEM_RATING_PKEY PRIMARY KEY (ID),
	CONSTRAINT ORDER_ITEM_RATING_ITEM_fK FOREIGN KEY (ORDER_RATING_ID)
        REFERENCES ORDER_RATING (ID),
	CONSTRAINT ORDER_ITEM_RATING_PRODUCT_fK FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT (ID)
);

