
CREATE TABLE IF NOT EXISTS SCHEDULER_DETAILS
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,  
    NAME CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT SCHEDULER_DETAILS_PKEY PRIMARY KEY (ID)
);