    INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('GOOGLE_MAP_KEY', 'default', false, true, now(), 1, now(), 1);
		
    INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('VENDOR_COMMISION_RATE', '0', false, true, now(), 1, now(), 1);
	
	INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('COMMISION_PER_ORDER', '0', false, true, now(), 1, now(), 1);
	
	INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('COMMISION_PER_REPLACE_ORDER', '0', false, true, now(), 1, now(), 1);
		
	INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('COMMISION_PER_RETURN_ORDER', '0', false, true, now(), 1, now(), 1);
	
	INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('ORDER_DELIVERY_CHARGE', '0', false, true, now(), 1, now(), 1);
		
	INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('DAY_MIN_ORDER_DELIVERED', '0', false, true, now(), 1, now(), 1);
	
	INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('INCENTIVE_AMOUNT_FOR_DAY', '0', false, true, now(), 1, now(), 1);
	

	
	
CREATE TABLE IF NOT EXISTS SETTING_HISTORY
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CURRENT_FIELD_VALUE CHARACTER VARYING(255) NOT NULL,
    FIELD_NAME CHARACTER VARYING(255)  NOT NULL,
    PREVIOUS_FIELD_VALUE CHARACTER VARYING(255)  NOT NULL,
    CONSTRAINT SETTING_HISTORY_PKEY PRIMARY KEY (ID)
);
	
	
	