

 INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('FACEBOOK_LINK', 'default', false, true, now(), 1, now(), 1);
	
	 INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('TWITTER_LINK', 'default', false, true, now(), 1, now(), 1);
	
	 INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('INSTAGRAM_LINK', 'default', false, true, now(), 1, now(), 1);
	
	 INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('LINKEDIN_LINK', 'default', false, true, now(), 1, now(), 1);
	
	 INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('YOUTUBE_LINK', 'default', false, true, now(), 1, now(), 1);
	
	 INSERT INTO SETTINGS(
	FIELD_NAME, FIELD_VALUE, ENCRYPTED, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
	VALUES ('GOOGLE_LINK', 'default', false, true, now(), 1, now(), 1);
	
	