-- Order table changes --
ALTER TABLE ORDERS ALTER COLUMN ADDRESS_ENGLISH DROP NOT NULL;
ALTER TABLE ORDERS ALTER COLUMN ADDRESS_ARABIC DROP NOT NULL;
ALTER TABLE ORDERS ALTER COLUMN FIRST_NAME DROP NOT NULL;
ALTER TABLE ORDERS ALTER COLUMN LAST_NAME DROP NOT NULL;
ALTER TABLE ORDERS ALTER COLUMN CITY_ID DROP NOT NULL;
ALTER TABLE ORDERS ALTER COLUMN STATE_ID DROP NOT NULL;
ALTER TABLE ORDERS ALTER COLUMN PINCODE_ID DROP NOT NULL;
ALTER TABLE ORDERS ALTER COLUMN PHONE_NUMBER DROP NOT NULL;


-- Online cart table changes --
ALTER TABLE ONLINE_CART ALTER COLUMN ADDRESS_ENGLISH DROP NOT NULL;
ALTER TABLE ONLINE_CART ALTER COLUMN ADDRESS_ARABIC DROP NOT NULL;
ALTER TABLE ONLINE_CART ALTER COLUMN CITY_ID DROP NOT NULL;
ALTER TABLE ONLINE_CART ALTER COLUMN FIRST_NAME DROP NOT NULL;
ALTER TABLE ONLINE_CART ALTER COLUMN LAST_NAME DROP NOT NULL;
ALTER TABLE ONLINE_CART ALTER COLUMN PHONE_NUMBER DROP NOT NULL;
ALTER TABLE ONLINE_CART ALTER COLUMN PINCODE_ID DROP NOT NULL;
ALTER TABLE ONLINE_CART ALTER COLUMN STATE_ID DROP NOT NULL;