ALTER TABLE SLIDER_IMAGE RENAME COLUMN 	APP_IMAGE_NAME TO IMAGE_NAME_ENGLISH;
ALTER TABLE SLIDER_IMAGE RENAME COLUMN APP_ORIGINAL_IMAGE_NAME TO IMAGE_ORIGIONAL_NAME_ENGLISH;

ALTER TABLE SLIDER_IMAGE ADD COLUMN IMAGE_NAME_ARABIC CHARACTER VARYING(255) DEFAULT ' ' NOT NULL;
ALTER TABLE SLIDER_IMAGE ADD COLUMN IMAGE_ORIGIONAL_NAME_ARABIC CHARACTER VARYING(255) DEFAULT ' ' NOT NULL;
ALTER TABLE SLIDER_IMAGE ADD COLUMN REDIRECT_URL CHARACTER VARYING(255);

