CREATE TABLE IF NOT EXISTS STOCK_ALLOCATION
(
    ID BIGINT NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    ALLOCATED_FOR CHARACTER VARYING(255) NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    VENDOR_ID BIGINT NOT NULL,
    DELIVERY_BOY_ID BIGINT,
    ORDER_ITEM_ID BIGINT NOT NULL,
    STOCK_DETAIL_ID BIGINT NOT NULL,
    TASK_ID BIGINT,
    CONSTRAINT STOCK_ALLOCATION_PK PRIMARY KEY(ID),
	CONSTRAINT STOCK_ALLOCATION_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
	CONSTRAINT STOCK_ALLOCATION_STOCK_DETIAL_FK FOREIGN KEY (STOCK_DETAIL_ID) REFERENCES STOCK_DETAILS(ID),
	CONSTRAINT STOCK_ALLOCATION_ORDER_ITEM_FK FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDERS_ITEM(ID),
	CONSTRAINT STOCK_ALLOCATION_DELIVERY_BOY_FK FOREIGN KEY (DELIVERY_BOY_ID) REFERENCES DELIVERY_BOY(ID),
	CONSTRAINT STOCK_ALLOCATION_TASK_FK FOREIGN KEY (TASK_ID) REFERENCES TASK(ID),
	CONSTRAINT STOCK_ALLOCATION_STORE_FK FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(ID),
	CONSTRAINT STOCK_ALLOCATION_UNIQUE UNIQUE(ORDER_ITEM_ID, STOCK_DETAIL_ID, ALLOCATED_FOR)
);


