

CREATE TABLE IF NOT EXISTS TICKET
(
    ID BIGSERIAL NOT NULL,
 	CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  	CREATED_BY NUMERIC(10,0) NOT NULL,
  	UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,		
  	UPDATED_BY NUMERIC(10,0) NOT NULL,
  	ACTIVE BOOLEAN NOT NULL,
    COMMENT CHARACTER VARYING(255),
    DESCRIPTION CHARACTER VARYING(255),
    EMAIL CHARACTER VARYING(255) NOT NULL,
    TICKET_REASON CHARACTER VARYING(255) NOT NULL,
    TICKET_STATUS CHARACTER VARYING(255) NOT NULL,
    USER_TYPE CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT TICKET_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TICKET_REASON
(
    ID BIGSERIAL NOT NULL,
 	CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  	CREATED_BY NUMERIC(10,0) NOT NULL,
  	UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,		
  	UPDATED_BY NUMERIC(10,0) NOT NULL,
  	ACTIVE BOOLEAN NOT NULL,
    REASON CHARACTER VARYING(255) NOT NULL,
    TYPE CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT TICKET_REASON_PKEY PRIMARY KEY (ID)
);
