CREATE TABLE IF NOT EXISTS TOPPING
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,  
	NAME CHARACTER VARYING(255) NOT NULL,
    DESCRIPTION CHARACTER VARYING(255),
    VENDOR_ID BIGINT NOT NULL,
    PRODUCT_FOOD_TYPE CHARACTER VARYING(255),
    CONSTRAINT TOPPING_PKEY PRIMARY KEY (ID),
   	CONSTRAINT TOPPING_VENDOR FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
	CONSTRAINT TOPPING_NAME_UNIQUE UNIQUE(VENDOR_ID, NAME)
);

ALTER TABLE PRODUCT_TOPPING DROP COLUMN IF EXISTS NAME;
ALTER TABLE PRODUCT_TOPPING DROP COLUMN IF EXISTS DESCRIPTION;
ALTER TABLE PRODUCT_TOPPING DROP COLUMN IF EXISTS PRODUCT_FOOD_TYPE;
ALTER TABLE PRODUCT_TOPPING ADD COLUMN IF NOT EXISTS TOPPING_ID BIGINT NOT NULL;
ALTER TABLE PRODUCT_TOPPING ADD CONSTRAINT PRODUCT_TOPPING_TOPPING FOREIGN KEY (TOPPING_ID) REFERENCES TOPPING (ID);