CREATE TABLE IF NOT EXISTS UOM
(
    ID BIGSERIAL NOT NULL,
    MEASUREMENT CHARACTER VARYING(128) NOT NULL,
    UOM_LABEL CHARACTER VARYING(255) NOT NULL,
    QUANTITY NUMERIC(10,2) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,   
    CONSTRAINT UOM_PKEY PRIMARY KEY (ID)
);