ALTER TABLE UOM  ADD COLUMN VENDOR_ID BIGINT;

ALTER TABLE PRODUCT_EXTRAS DROP COLUMN NAME;

ALTER TABLE PRODUCT_EXTRAS DROP COLUMN DESCRIPTION;

ALTER TABLE PRODUCT_EXTRAS  ADD COLUMN PRODUCT_EXTRAS_MASTER_ID BIGINT;


CREATE TABLE PRODUCT_EXTRAS_MASTER
(
    ID BIGSERIAL NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    DESCRIPTION CHARACTER VARYING(255),
    NAME CHARACTER VARYING(255) NOT NULL,
    RATE DOUBLE PRECISION NOT NULL,
    VENDOR_ID BIGINT NOT NULL,
    CONSTRAINT PRODUCT_EXTRAS_MASTER_PKEY PRIMARY KEY (ID)
);


ALTER TABLE PRODUCT_EXTRAS  ADD CONSTRAINT PRODUCT_EXTRAS_MASTER_PRODUCT_EXTRAS_FK FOREIGN KEY (PRODUCT_EXTRAS_MASTER_ID)
        REFERENCES PRODUCT_EXTRAS_MASTER (ID);

