CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGSERIAL NOT NULL,
    FIRST_NAME CHARACTER VARYING(255) NOT NULL,
    LAST_NAME CHARACTER VARYING(255) NOT NULL,
    EMAIL CHARACTER VARYING(255) NOT NULL,
    ROLE CHARACTER VARYING(255) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CONSTRAINT USERS_PKEY PRIMARY KEY (ID),
    CONSTRAINT USERS_UNIQUE_EMAIL UNIQUE (EMAIL)
);