ALTER TABLE IF EXISTS VENDOR ADD COLUMN IF NOT EXISTS PROFILE_COMPLETED BOOLEAN default false;
ALTER TABLE IF EXISTS VENDOR DROP COLUMN IF EXISTS DELIVERY_FEE;

UPDATE VENDOR SET STATUS = 'Verification Pending' WHERE STATUS = 'Verification_Pending';