CREATE TABLE IF NOT EXISTS VENDOR_CUISINE
(
    ID BIGSERIAL NOT NULL,
    VENDOR_ID BIGINT NOT NULL,
    CUISINE_ID BIGINT NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CONSTRAINT VENDOR_CUISINE_PKEY PRIMARY KEY (ID),
    CONSTRAINT VENDOR_CUISINE_UNIQUE_KEY UNIQUE (VENDOR_ID,CUISINE_ID),
    CONSTRAINT VENDOR_CUISINE_VENDOR FOREIGN KEY (VENDOR_ID)
        REFERENCES VENDOR (ID),
    CONSTRAINT VENDOR_CUISINE_CUISINE FOREIGN KEY (CUISINE_ID)
        REFERENCES CUISINE (ID) 
);

ALTER TABLE VENDOR 
DROP COLUMN OPENING_HOURS;

ALTER TABLE VENDOR
ADD COLUMN OPENING_HOURS_FROM TIME WITH TIME ZONE;

ALTER TABLE VENDOR
ADD COLUMN OPENING_HOURS_TO TIME WITH TIME ZONE;
