CREATE TABLE IF NOT EXISTS VENDOR_PAYMENT
(
    ID BIGSERIAL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,  
	VENDOR_ID BIGINT NOT NULL,
	SUBSCRIPTION_PLAN_ID BIGINT NOT NULL,
	VENDOR_ORDER_ID CHARACTER VARYING(255) NOT NULL,
	PAYMENT_TOKEN CHARACTER VARYING(255),
	PAYMENT_ID CHARACTER VARYING(255),
	STATUS CHARACTER VARYING(255) NOT NULL,
	ADMINISTRATIVE_CHARGE NUMERIC(10,2),
	AMOUNT NUMERIC(10,2) NOT NULL,
    CONSTRAINT VENDOR_PAYMENT_PKEY PRIMARY KEY (ID),
    CONSTRAINT VENDOR_PAYMENT_VENDOR
  		FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR,
  	CONSTRAINT VENDOR_PAYMENT_SUBSCRIPTION_PLAN
  		FOREIGN KEY (SUBSCRIPTION_PLAN_ID) REFERENCES SUBSCRIPTION_PLAN
);
