package com.nice.util;

/**
 * @author : Kody Technolab PVT. LTD.
 * @date   : 30-Jun-2020
 */
public enum EmailTemplatesEnum {

	OTP, WELCOME, EMAIL_VERIFICATION_LINK, EMAIL_VERIFICATION_BOTH, EMAIL_VERIFICATION_OTP, FORGOT_PASSWORD_LINK, FORGOT_PASSWORD_BOTH, FORGOT_PASSWORD_OTP,EMAIL_VERIFICATION, OTP_VERIFICATION, SUBSCRIPTION_EXPIRE_REMINDER
}
